### ISSUE TITLE
Reopen - Tiff's patches are broken with latests commits of config.sub

### ISSUE THREAD

**Issue by rstevens011** [ps3dev/ps3libraries#35]
patching still fails as of the latest commit from the config.sub repo:

```
<SNIP>
tiff-3.9.4/tools/tiffgt.c
patching file config/config.sub
Hunk #1 FAILED at 1038.
1 out of 1 hunk FAILED -- saving rejects to file config/config.sub.rej
patching file contrib/iptcutil/iptcutil.c
../scripts/010-tiff-3.9.4.sh: Failed.
../scripts/009-ps3libraries.sh: Failed.
ERROR: Could not run the toolchain script.
```

_Originally posted by @rstevens011 in 
https://github.com/ps3dev/ps3libraries/issues/34

**Comment by zeldin** [comment]
Please use the "Reopen issue" button to reopen an issue rather than creating a duplicate one...

**Comment by rstevens011** [comment]
Apologies but I do not see a reopen button. I was not the original reporter nor am I a collaborator. See https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github#21333938 for an explanation.

Sent from my iPhone

On Sep 20, 2018, at 11:20 PM, Marcus Comstedt <notifications@github.com<mailto:notifications@github.com>> wrote:


Please use the "Reopen issue" button to reopen an issue rather than creating a duplicate one...

**Comment by zeldin** [comment]
Huh, that's weird.  And judging by the comments I'm not alone in thinking that.  :smiley: 
No worries, I'll reopen it for you then.
