### ISSUE TITLE
Downloading freetype source gives 404 error

### ISSUE THREAD

**Issue by rhynec** [ps3dev/ps3libraries#54]
Currently, compiling the ps3toolchain fails because the script for freetype is unable to download the source code for the version of the library being used. The source code has been moved to: http://download.savannah.gnu.org/releases/freetype/freetype-old/freetype-2.4.3.tar.gz (They just moved older releases to freetype-old, apparently).

Changing the URL should fix compilation problems.

**Comment by bucanero** [comment]
This should be fixed by merging #53

**Comment by zeldin** [comment]
Fixed by #53
