### ISSUE TITLE
Update zlib-1.2.11 to zlib-1.2.12

### ISSUE THREAD

**Issue by stranno** [ps3dev/ps3libraries#56]
Toolchain fails since zlib-1.2.11 no longer available on their servers.

**Comment by miigotu** [comment]
I can't speak for everyone, but I have been quite busy with other projects. I'm not sure when/if I will have time personally to update the scripts, but if you are able to a pull request would be much appreciated. Just follow the same code stile we already use in the existing scripts. Maybe @bucanero could assist?

**Comment by miigotu** [comment]
Fixed in #57

**Comment by bucanero** [comment]
apologies @miigotu , I couldn't check this issue but it looks that it has been fixed already 👍
